// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Título (deixa como está) field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.document_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  document_title: prismic.KeyTextField;

  /**
   * Cor do fundo dos links field in *Layout*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links_color_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  links_color_background: prismic.ColorField;

  /**
   * Cor do texto dos links field in *Layout*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links_color_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  links_color_text: prismic.ColorField;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    'layout',
    Lang
  >;

/**
 * Item in *Link → Links*
 */
export interface LinkDocumentDataLinksItem {
  /**
   * Imagem field in *Link → Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link.links[].thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Título field in *Link → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.links[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * URL do link field in *Link → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://
   * - **API ID Path**: link.links[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;
}

/**
 * Content for Link documents
 */
interface LinkDocumentData {
  /**
   * Título do documento (ignorar) field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Links
   * - **API ID Path**: link.doc_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  doc_title: prismic.KeyTextField;

  /**
   * Links field in *Link*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<LinkDocumentDataLinksItem>>;
}

/**
 * Link document from Prismic
 *
 * - **API ID**: `link`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LinkDocumentData>, 'link', Lang>;

/**
 * Content for Perfil documents
 */
interface ProfileDocumentData {
  /**
   * @ do Instagram field in *Perfil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.instagram_profile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram_profile: prismic.KeyTextField;

  /**
   * Foto de perfil field in *Perfil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.profile_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Título field in *Perfil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Raíza Souto
   * - **API ID Path**: profile.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descrição field in *Perfil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Perfil document from Prismic
 *
 * - **API ID**: `profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfileDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProfileDocumentData>,
    'profile',
    Lang
  >;

export type AllDocumentTypes = LayoutDocument | LinkDocument | ProfileDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LayoutDocument,
      LayoutDocumentData,
      LinkDocument,
      LinkDocumentData,
      LinkDocumentDataLinksItem,
      ProfileDocument,
      ProfileDocumentData,
      AllDocumentTypes,
    };
  }
}
